spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 150422
    url: jdbc:mysql://localhost:3306/api_project?serverTimezone=Asia/Shanghai
#  redis:
#    host: 192.168.62.128
#    port: 6379
#    database: 0
#    password: 150422
#  session:
#    store-type: redis # redis存储session会话
  mybatis-plus:
    global-config:
      db-config:
        logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值
        logic-not-delete-value: 0 # 逻辑未删除值
logging:
  level:
    root: info
    com.vansven.api.mapper: trace
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: api开放平台
    email: 2946307091@qq.com
    concat: vansven
    url: https://localhost:8080/doc.html
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.vansven.api.controller
neu:
  vansven:
    client:
      publickey: aaaa
      privatekey: vansvenfan

server:
  servlet:
    session:
      timeout: 3600
    context-path: /vansven
  port: 8080